approvedGitRepositories:
  - "**"

catalog:
  "@inlang/cli": ^3.2.0
  "@inlang/paraglide-js": ^2.23.0
  "@playwright/test": ^1.62.0
  "@solidjs/router": ^0.16.2
  "@tailwindcss/vite": ^4.3.3
  "@types/node": ^26.1.1
  daisyui: ^5.7.4
  lefthook: ^2.1.10
  oxfmt: ^0.60.0
  oxlint: ^1.75.0
  oxlint-tsgolint: ^7.0.2001
  solid-js: ^1.9.14
  tailwindcss: ^4.3.3
  typescript: ^7.0.2
  vite: ^8.1.5
  vite-plugin-solid: ^2.11.14

checksumBehavior: update

enableScripts: true

nodeLinker: pnpm

npmMinimalAgeGate: 1d
